### ISSUE TITLE
Tool fails if there is no table prefix

### ISSUE THREAD

**Issue by SotonianRed** [EsriUK/OSMM-Styling#8]
I've translated the raw .gz compressed .gml data into .shp using ogr2ogr translators.  I then load the resulting shapefiles into a FGDB using the Import tool in ArcCatalog but there is nowhere in this process to add a table prefix so when I then go to try and run the tool it errors.

![error](https://user-images.githubusercontent.com/9025319/58635258-5368a780-82e5-11e9-8b82-a344fd73995b.png)

I've trawled through ESRI/Google looking to see if there is a way to add a prefix to my FGDB retrospectively but to no avail at the moment!

Is there a workaround that I could try to get around this?

**Comment by petermcdaid** [comment]
The tool is designed for use with data loaded through Esri UK's ProductivitySuite software. The scripts are specific to the data structure created by that tool. Manually adding a prefix is unlikely to allow the script to work as there will be other field name etc that it is expecting.

I have added a note make it clearer in the description that this is for use with data created in that way.

**Comment by SotonianRed** [comment]
Thanks for the very quick reply Peter!  I did wonder if this was the case!

If I may ask another question related to this, what will happen then when PS is eventually phased out, which I believe is on the cards?
